name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      
      - name: Install packages
        run: bun install
      
      - name: Build files
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
  
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
    
